public enum ProfessionalSkills {
    CIVIL_ENGINEER,
    MASTER_OF_CONSTRUCTION_WORKS,
    MASTER_OF_INSTALLATION_WORKS,
    CRANE_OPERATOR,
    REINFORCED_CONCRETE_WORKER,
    CARPENTER,
    ROOFER,
    CONCRETE_WORKER,
    MASON,
    LINER_FOR_INDOOR_AND_OUTDOOR_USE,
    PAINTER_PLASTERER,
    ELECTRIC_AND_GAS_WELDER
}